### PR TITLE
Fix text editor cursor placement #514

### PR DESCRIPTION
**Pull request by PhearZero**
### #514 - Fix text editor cursor placement
Working on resolving the cursor placement issue. Binding to the value of an input will cause the vDOM to re-render. I've used the [ReactLink](https://facebook.github.io/react/docs/two-way-binding-helpers.html) method for a two way data bind to value via the [react-link](https://github.com/mdarse/react-link) helper function and valueLink property. Still looking into the other forms

### CODE REVIEW

**Comment by saikat** [comment]
This was originally a bug in react-formal that they should have fixed.  The
bug doesn't arise when we have a form component standalone outside of a
react-formal form.  Maybe see if the bug is still a react-formal issue and
maybe we can work around it?  I'm also wary of using valueLink.

**Comment by PhearZero** [comment]
For sure! I have a vanilla react-form with material-ui with no issues. The commit last commits are not for react-formal but for the [SendEventMail](../blob/master/src/frontend/components/SendEventMail.js) which was exhibiting the same behavior but with material-ui components. In the case of the SendEventMail, the state was already being updated in the onChange event and the bind of value was causing the redraw. Not sure about the rest!

**Comment by bahoo** [comment]
@PhearZero Could I sweet-talk you into applying this magic to [AdminEventEmailCreationForm](https://github.com/Bernie-2016/ground-control/blob/master/src/frontend/components/AdminEventEmailCreationForm.js) and [FastFwdForm](https://github.com/Bernie-2016/ground-control/blob/master/src/frontend/components/FastFwdForm.js) as well? :)

**Comment by PhearZero** [comment]
@bahoo Got ya covered! Give me twenty-thirty to wrap up an update to the esm-api

**Comment by PhearZero** [comment]
@bahoo Haven't gotten around to the other forms to triple check but FastFwd, AdminEvenetEmailCreation and SendEventMail are patched. I think I still have a few forms that haven't been patched

**Comment by PhearZero** [comment]
That's the last of them that I can find.

**Comment by bahoo** [comment]
@PhearZero One thing I noticed, as you type your message in the FastFwd admin, it continues to randomize / shuffle the list of nearby people. Any remedy there? Doesn't affect the core experience really, but a little odd. Also, when I submitted the first time, it flipped Test Mode to true (it appeared to do some kind of small reset to defaults on the form) but I couldn't repro it after a few more tries.

Those are minor, and may or may not be worth looking into. I'm going to go ahead and deploy your branch and resolve #514. Thanks, Mike!

**Pull request closed without merging**
