### PR TITLE
Use reverse-proxy for Slack signup apps (fixes #645)

### LINKED ISSUE #645: Use reverse-proxy for slack signup apps
I've got a start on this here: https://github.com/Bernie-2016/ground-control/tree/add-proxies

### PR DESCRIPTION
**Pull request by maclover7**
cc @jlegrone

### CODE REVIEW

**Comment by jlegrone** [comment]
@maclover7 have you tested the signup forms? I'm getting a 404 on submit.

**Comment by maclover7** [comment]
I haven't tested them, but it looks like they were added here --> https://github.com/Bernie-2016/ground-control/commit/6e2d1100abb694c9f24fa64b97a55693a77df6d0

**Comment by jlegrone** [comment]
@maclover7 yes, an important part of this is making sure those forms submit successfully so it's something we need to test.

**Comment by jlegrone** [comment]
New plan: bring slack invites into ground control react components and group all invites on one page at `/slack`.

**Comment by maclover7** [comment]
Updated PR to use a React component. We will need to get the Slack API keys from the fleet of Heroku apps currently being used.

**Comment by jlegrone** [comment]
Let's refactor to use `request-promise` and async/await pattern instead of callbacks. These forms get a lot of mobile traffic too so they'll also need to be responsive and mobile friendly!

**Comment by jlegrone** [comment]
Also take a look at #658

**Comment by maclover7** [comment]
Addressed #658 via https://github.com/Bernie-2016/ground-control/pull/653/commits/5c59a217e9541421094fea2f52d6045c758ff36e.

**Comment by maclover7** [comment]
👍 Thanks @jlegrone!!

**Pull request merged**
